import type { Creance, Depense, Dette, ObjectifsFinanciers } from "./types";

/** Décale une date de N jours par rapport à aujourd'hui (ISO complet). */
const j = (jours: number, heure = 10) => {
  const d = new Date();
  d.setDate(d.getDate() + jours);
  d.setHours(heure, 0, 0, 0);
  return d.toISOString();
};

export const depensesDemo: Depense[] = [
  {
    id: "D-0001",
    date: j(0, 9),
    montant: 2000,
    categorie: "transport",
    modePaiement: "especes",
    description: "Livraison de commandes clients — quartier Badalabougou",
    responsable: "Moussa Koné",
    statut: "payee",
    justificatif: { nom: "recu-transport.jpg", type: "image/jpeg", taille: 184320 },
    source: "manuelle",
  },
  {
    id: "D-0002",
    date: j(-1, 16),
    montant: 6000,
    categorie: "marketing",
    modePaiement: "orange_money",
    description: "Campagne de publicité WhatsApp et affiches boutique",
    responsable: "Aïcha Traoré",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0003",
    date: j(-2, 11),
    montant: 4000,
    categorie: "internet",
    modePaiement: "orange_money",
    description: "Recharge forfait internet boutique",
    responsable: "Kadiatou Sow",
    statut: "payee",
    justificatif: { nom: "facture-internet.pdf", type: "application/pdf", taille: 96000 },
    source: "manuelle",
  },
  {
    id: "D-0004",
    date: j(-3, 8),
    montant: 25000,
    categorie: "loyer",
    modePaiement: "virement",
    description: "Loyer mensuel du magasin principal",
    responsable: "Bekaye Sora",
    statut: "payee",
    justificatif: { nom: "quittance-loyer.pdf", type: "application/pdf", taille: 142000 },
    source: "manuelle",
  },
  {
    id: "D-0005",
    date: j(-4, 15),
    montant: 7000,
    categorie: "electricite",
    modePaiement: "especes",
    description: "Facture EDM du mois",
    responsable: "Kadiatou Sow",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0006",
    date: j(-6, 12),
    montant: 3000,
    categorie: "transport",
    modePaiement: "especes",
    description: "Carburant véhicule de livraison",
    responsable: "Salif Doumbia",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0007",
    date: j(-8, 10),
    montant: 8000,
    categorie: "impots",
    modePaiement: "virement",
    description: "Acompte de patente trimestrielle",
    responsable: "Bekaye Sora",
    statut: "en_attente",
    justificatif: { nom: "avis-impot.pdf", type: "application/pdf", taille: 210000 },
    source: "manuelle",
  },
  {
    id: "D-0008",
    date: j(-11, 14),
    montant: 3000,
    categorie: "autres",
    modePaiement: "especes",
    description: "Produits d'entretien et fournitures de boutique",
    responsable: "Awa Cissé",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0009",
    date: j(-14, 9),
    montant: 7000,
    categorie: "marketing",
    modePaiement: "wave",
    description: "Séance photo produits pour les réseaux sociaux",
    responsable: "Aïcha Traoré",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0010",
    date: j(-18, 11),
    montant: 2500,
    categorie: "transport",
    modePaiement: "especes",
    description: "Transport de marchandises depuis le port",
    responsable: "Salif Doumbia",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0011",
    date: j(-26, 8),
    montant: 25000,
    categorie: "loyer",
    modePaiement: "virement",
    description: "Loyer du mois précédent",
    responsable: "Bekaye Sora",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0012",
    date: j(-29, 17),
    montant: 6500,
    categorie: "electricite",
    modePaiement: "especes",
    description: "Facture EDM du mois précédent",
    responsable: "Kadiatou Sow",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0013",
    date: j(-35, 10),
    montant: 4500,
    categorie: "autres",
    modePaiement: "especes",
    description: "Réparation de la climatisation du magasin",
    responsable: "Salif Doumbia",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0014",
    date: j(-44, 9),
    montant: 5000,
    categorie: "marketing",
    modePaiement: "orange_money",
    description: "Distribution de flyers marché de Médina",
    responsable: "Aïcha Traoré",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
  {
    id: "D-0015",
    date: j(-58, 8),
    montant: 25000,
    categorie: "loyer",
    modePaiement: "virement",
    description: "Loyer du magasin",
    responsable: "Bekaye Sora",
    statut: "payee",
    justificatif: null,
    source: "manuelle",
  },
];

export const creancesDemo: Creance[] = [
  {
    id: "C-0001",
    clientId: null,
    nom: "Salon Belle Éclat",
    montant: 48000,
    date: j(-12),
    echeance: j(6),
    regle: false,
    observation: "Commande mensuelle réglée par tranches.",
  },
  {
    id: "C-0002",
    clientId: null,
    nom: "Institut Éclat d'Or",
    montant: 62000,
    date: j(-25),
    echeance: j(-5),
    regle: false,
    observation: "Relance téléphonique effectuée.",
  },
  {
    id: "C-0003",
    clientId: null,
    nom: "Boutique Nour",
    montant: 26000,
    date: j(-8),
    echeance: j(12),
    regle: false,
    observation: "",
  },
  {
    id: "C-0004",
    clientId: null,
    nom: "Oumar Diarra",
    montant: 14000,
    date: j(-30),
    echeance: j(-12),
    regle: false,
    observation: "Client fidèle, paiement partiel promis.",
  },
  {
    id: "C-0005",
    clientId: null,
    nom: "Mariam Cissé",
    montant: 9000,
    date: j(-40),
    echeance: j(-20),
    regle: true,
    observation: "Réglé en espèces à la boutique.",
  },
];

export const dettesDemo: Dette[] = [
  {
    id: "F-0001",
    fournisseurId: null,
    fournisseur: "Cosmetic Import SARL",
    montant: 160000,
    date: j(-18),
    echeance: j(9),
    regle: false,
    observation: "Crédit 30 jours sur la commande d'avril.",
  },
  {
    id: "F-0002",
    fournisseurId: null,
    fournisseur: "Distribution Sahel",
    montant: 74000,
    date: j(-33),
    echeance: j(-3),
    regle: false,
    observation: "Échéance dépassée, à régulariser.",
  },
  {
    id: "F-0003",
    fournisseurId: null,
    fournisseur: "Emballages Niger Plus",
    montant: 38000,
    date: j(-10),
    echeance: j(20),
    regle: false,
    observation: "",
  },
  {
    id: "F-0004",
    fournisseurId: null,
    fournisseur: "Karité Nature Koulikoro",
    montant: 27000,
    date: j(-45),
    echeance: j(-15),
    regle: true,
    observation: "Payé par virement.",
  },
];

export const objectifsDemo: ObjectifsFinanciers = {
  chiffreAffaires: 500000,
  benefice: 150000,
  plafondDepenses: 1500000,
};
