import creme from "@/assets/produit-creme.jpg";
import huile from "@/assets/produit-huile.jpg";
import lingettes from "@/assets/produit-lingettes.jpg";
import lotion from "@/assets/produit-lotion.jpg";
import savon from "@/assets/produit-savon.jpg";
import serum from "@/assets/produit-serum.jpg";

import type { LigneHistorique, MouvementStock, Produit } from "./types";

export const CATEGORIES = ["Soins du visage", "Soins du corps", "Hygiène", "Accessoires"] as const;

export const MARQUES = ["501", "501 Premium", "501 Nature"] as const;

export const FOURNISSEURS = [
  "Cosmetic Import SARL",
  "Distribution Sahel",
  "Beauty Africa Group",
  "Atelier 501",
] as const;

const j = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const produitsDemo: Produit[] = [
  {
    id: "P-001",
    nom: "Lotion Éclaircissante 501",
    description:
      "Lotion tonique éclaircissante à l'extrait de karité, unifie le teint et hydrate en profondeur. Flacon 500 ml.",
    marque: "501",
    categorie: "Soins du corps",
    codeBarres: "6001501000017",
    unite: "Bouteille",
    prixAchat: 3200,
    prixVente: 5500,
    stock: 148,
    stockMinimum: 30,
    dateExpiration: j(-420),
    fournisseur: "Cosmetic Import SARL",
    actif: true,
    image: lotion,
    dateAjout: j(210),
    dateModification: j(3),
  },
  {
    id: "P-002",
    nom: "Savon 501",
    description:
      "Savon dermo-purifiant enrichi en glycérine végétale, pour une peau nette et douce. Pain de 200 g.",
    marque: "501",
    categorie: "Hygiène",
    codeBarres: "6001501000024",
    unite: "Pièce",
    prixAchat: 650,
    prixVente: 1250,
    stock: 24,
    stockMinimum: 40,
    dateExpiration: j(-300),
    fournisseur: "Atelier 501",
    actif: true,
    image: savon,
    dateAjout: j(198),
    dateModification: j(1),
  },
  {
    id: "P-003",
    nom: "Lingettes 501",
    description:
      "Lingettes nettoyantes démaquillantes, sans alcool, adaptées à toutes les peaux. Paquet de 25 lingettes.",
    marque: "501 Nature",
    categorie: "Hygiène",
    codeBarres: "6001501000031",
    unite: "Sachet",
    prixAchat: 900,
    prixVente: 1800,
    stock: 0,
    stockMinimum: 25,
    dateExpiration: j(-120),
    fournisseur: "Distribution Sahel",
    actif: true,
    image: lingettes,
    dateAjout: j(160),
    dateModification: j(6),
  },
  {
    id: "P-004",
    nom: "Crème Hydratante 501",
    description:
      "Crème riche à l'aloe vera et beurre de cacao, nourrit intensément les peaux sèches. Pot 250 ml.",
    marque: "501 Premium",
    categorie: "Soins du visage",
    codeBarres: "6001501000048",
    unite: "Pièce",
    prixAchat: 4200,
    prixVente: 7500,
    stock: 76,
    stockMinimum: 20,
    dateExpiration: j(-60),
    fournisseur: "Beauty Africa Group",
    actif: true,
    image: creme,
    dateAjout: j(140),
    dateModification: j(9),
  },
  {
    id: "P-005",
    nom: "Huile Corporelle 501",
    description:
      "Huile sèche satinée aux huiles de baobab et d'argan, sublime et protège la peau. Flacon 200 ml.",
    marque: "501 Premium",
    categorie: "Soins du corps",
    codeBarres: "6001501000055",
    unite: "Flacon",
    prixAchat: 5100,
    prixVente: 9000,
    stock: 42,
    stockMinimum: 15,
    dateExpiration: j(-500),
    fournisseur: "Cosmetic Import SARL",
    actif: true,
    image: huile,
    dateAjout: j(120),
    dateModification: j(12),
  },
  {
    id: "P-006",
    nom: "Sérum Éclat 501",
    description:
      "Sérum concentré vitamine C, réduit les taches et illumine le teint. Flacon compte-gouttes 30 ml.",
    marque: "501 Premium",
    categorie: "Soins du visage",
    codeBarres: "6001501000062",
    unite: "Flacon",
    prixAchat: 6800,
    prixVente: 12500,
    stock: 18,
    stockMinimum: 20,
    dateExpiration: j(-45),
    fournisseur: "Beauty Africa Group",
    actif: true,
    image: serum,
    dateAjout: j(95),
    dateModification: j(2),
  },
  {
    id: "P-007",
    nom: "Gel Douche 501 Nature",
    description: "Gel douche parfum karité-vanille, formule douce sans savon. Bouteille 750 ml.",
    marque: "501 Nature",
    categorie: "Hygiène",
    codeBarres: "6001501000079",
    unite: "Bouteille",
    prixAchat: 2100,
    prixVente: 3900,
    stock: 210,
    stockMinimum: 40,
    dateExpiration: j(-700),
    fournisseur: "Distribution Sahel",
    actif: true,
    image: null,
    dateAjout: j(80),
    dateModification: j(15),
  },
  {
    id: "P-008",
    nom: "Coffret Découverte 501",
    description: "Coffret cadeau : lotion, savon et crème format voyage.",
    marque: "501",
    categorie: "Accessoires",
    codeBarres: "6001501000086",
    unite: "Carton",
    prixAchat: 9500,
    prixVente: 16500,
    stock: 9,
    stockMinimum: 5,
    dateExpiration: null,
    fournisseur: "Atelier 501",
    actif: false,
    image: null,
    dateAjout: j(60),
    dateModification: j(20),
  },
  {
    id: "P-009",
    nom: "Lait de Toilette 501",
    description: "Lait démaquillant onctueux pour le visage et le cou. Flacon 400 ml.",
    marque: "501",
    categorie: "Soins du visage",
    codeBarres: "6001501000093",
    unite: "Bouteille",
    prixAchat: 2800,
    prixVente: 4900,
    stock: 65,
    stockMinimum: 25,
    dateExpiration: j(-30),
    fournisseur: "Cosmetic Import SARL",
    actif: true,
    image: null,
    dateAjout: j(48),
    dateModification: j(4),
  },
  {
    id: "P-010",
    nom: "Éponge Exfoliante 501",
    description: "Éponge de massage exfoliante réutilisable, texture douce.",
    marque: "501 Nature",
    categorie: "Accessoires",
    codeBarres: "6001501000109",
    unite: "Pièce",
    prixAchat: 450,
    prixVente: 1000,
    stock: 130,
    stockMinimum: 30,
    dateExpiration: null,
    fournisseur: "Distribution Sahel",
    actif: true,
    image: null,
    dateAjout: j(35),
    dateModification: j(7),
  },
  {
    id: "P-011",
    nom: "Beurre de Karité 501",
    description: "Beurre de karité pur non raffiné, multi-usages. Pot 500 g.",
    marque: "501 Nature",
    categorie: "Soins du corps",
    codeBarres: "6001501000116",
    unite: "Pièce",
    prixAchat: 1800,
    prixVente: 3500,
    stock: 3,
    stockMinimum: 15,
    dateExpiration: j(-15),
    fournisseur: "Atelier 501",
    actif: true,
    image: null,
    dateAjout: j(28),
    dateModification: j(5),
  },
  {
    id: "P-012",
    nom: "Déodorant Fraîcheur 501",
    description: "Déodorant roll-on 48 h, sans alcool. Flacon 50 ml.",
    marque: "501",
    categorie: "Hygiène",
    codeBarres: "6001501000123",
    unite: "Pièce",
    prixAchat: 1200,
    prixVente: 2400,
    stock: 88,
    stockMinimum: 25,
    dateExpiration: j(-250),
    fournisseur: "Beauty Africa Group",
    actif: true,
    image: null,
    dateAjout: j(21),
    dateModification: j(8),
  },
];

const h = (jours: number, heures: number) =>
  new Date(Date.now() - jours * 86_400_000 - heures * 3_600_000).toISOString();

export const mouvementsDemo: MouvementStock[] = [
  {
    id: "M-001",
    produitId: "P-001",
    date: h(0, 2),
    type: "sortie",
    utilisateur: "Aïcha Traoré",
    quantite: 12,
    observation: "Vente comptoir VTE-2481",
  },
  {
    id: "M-002",
    produitId: "P-003",
    date: h(0, 5),
    type: "sortie",
    utilisateur: "Moussa Diallo",
    quantite: 8,
    observation: "Dernier stock écoulé",
  },
  {
    id: "M-003",
    produitId: "P-004",
    date: h(1, 3),
    type: "entree",
    utilisateur: "Bekaye Sora",
    quantite: 60,
    observation: "Réception Beauty Africa Group",
  },
  {
    id: "M-004",
    produitId: "P-002",
    date: h(1, 7),
    type: "sortie",
    utilisateur: "Fatou Camara",
    quantite: 20,
    observation: "Commande boutique Kalaban",
  },
  {
    id: "M-005",
    produitId: "P-005",
    date: h(2, 1),
    type: "entree",
    utilisateur: "Bekaye Sora",
    quantite: 30,
    observation: "Réception Cosmetic Import SARL",
  },
  {
    id: "M-006",
    produitId: "P-011",
    date: h(2, 6),
    type: "sortie",
    utilisateur: "Aïcha Traoré",
    quantite: 14,
    observation: "Vente en gros",
  },
  {
    id: "M-007",
    produitId: "P-006",
    date: h(3, 2),
    type: "sortie",
    utilisateur: "Moussa Diallo",
    quantite: 6,
    observation: "Vente comptoir VTE-2455",
  },
  {
    id: "M-008",
    produitId: "P-007",
    date: h(4, 4),
    type: "entree",
    utilisateur: "Bekaye Sora",
    quantite: 120,
    observation: "Réapprovisionnement mensuel",
  },
  {
    id: "M-009",
    produitId: "P-009",
    date: h(5, 2),
    type: "sortie",
    utilisateur: "Fatou Camara",
    quantite: 10,
    observation: "Transfert dépôt secondaire",
  },
  {
    id: "M-010",
    produitId: "P-012",
    date: h(6, 3),
    type: "entree",
    utilisateur: "Bekaye Sora",
    quantite: 48,
    observation: "Réception Beauty Africa Group",
  },
  {
    id: "M-011",
    produitId: "P-010",
    date: h(7, 5),
    type: "sortie",
    utilisateur: "Aïcha Traoré",
    quantite: 25,
    observation: "Vente marché de Sébénikoro",
  },
  {
    id: "M-012",
    produitId: "P-001",
    date: h(8, 2),
    type: "entree",
    utilisateur: "Bekaye Sora",
    quantite: 100,
    observation: "Réception conteneur",
  },
];

export const ventesDemo: LigneHistorique[] = [
  {
    id: "V-001",
    produitId: "P-001",
    date: h(0, 2),
    reference: "VTE-2481",
    tiers: "Awa Koné",
    quantite: 12,
    montant: 66000,
  },
  {
    id: "V-002",
    produitId: "P-001",
    date: h(3, 4),
    reference: "VTE-2460",
    tiers: "Boutique Hamdallaye",
    quantite: 25,
    montant: 137500,
  },
  {
    id: "V-003",
    produitId: "P-002",
    date: h(1, 7),
    reference: "VTE-2472",
    tiers: "Boutique Kalaban",
    quantite: 20,
    montant: 25000,
  },
  {
    id: "V-004",
    produitId: "P-003",
    date: h(0, 5),
    reference: "VTE-2479",
    tiers: "Client comptoir",
    quantite: 8,
    montant: 14400,
  },
  {
    id: "V-005",
    produitId: "P-004",
    date: h(2, 3),
    reference: "VTE-2465",
    tiers: "Salon Éclat",
    quantite: 10,
    montant: 75000,
  },
  {
    id: "V-006",
    produitId: "P-005",
    date: h(4, 1),
    reference: "VTE-2451",
    tiers: "Mariam Sidibé",
    quantite: 4,
    montant: 36000,
  },
  {
    id: "V-007",
    produitId: "P-006",
    date: h(3, 2),
    reference: "VTE-2455",
    tiers: "Client comptoir",
    quantite: 6,
    montant: 75000,
  },
  {
    id: "V-008",
    produitId: "P-011",
    date: h(2, 6),
    reference: "VTE-2468",
    tiers: "Grossiste Médina",
    quantite: 14,
    montant: 49000,
  },
];

export const achatsDemo: LigneHistorique[] = [
  {
    id: "A-001",
    produitId: "P-001",
    date: h(8, 2),
    reference: "ACH-1042",
    tiers: "Cosmetic Import SARL",
    quantite: 100,
    montant: 320000,
  },
  {
    id: "A-002",
    produitId: "P-004",
    date: h(1, 3),
    reference: "ACH-1051",
    tiers: "Beauty Africa Group",
    quantite: 60,
    montant: 252000,
  },
  {
    id: "A-003",
    produitId: "P-005",
    date: h(2, 1),
    reference: "ACH-1048",
    tiers: "Cosmetic Import SARL",
    quantite: 30,
    montant: 153000,
  },
  {
    id: "A-004",
    produitId: "P-007",
    date: h(4, 4),
    reference: "ACH-1046",
    tiers: "Distribution Sahel",
    quantite: 120,
    montant: 252000,
  },
  {
    id: "A-005",
    produitId: "P-012",
    date: h(6, 3),
    reference: "ACH-1044",
    tiers: "Beauty Africa Group",
    quantite: 48,
    montant: 57600,
  },
];
