/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SortiesStockRouteImport } from './routes/sorties-stock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalairesRouteImport } from './routes/salaires'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as EntreesStockRouteImport } from './routes/entrees-stock'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VentesIndexRouteImport } from './routes/ventes.index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as InventaireIndexRouteImport } from './routes/inventaire.index'
import { Route as FournisseursIndexRouteImport } from './routes/fournisseurs.index'
import { Route as EntreesStockIndexRouteImport } from './routes/entrees-stock.index'
import { Route as EmployesIndexRouteImport } from './routes/employes.index'
import { Route as DepensesIndexRouteImport } from './routes/depenses.index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as VentesRetoursRouteImport } from './routes/ventes.retours'
import { Route as VentesHistoriqueRouteImport } from './routes/ventes.historique'
import { Route as ProduitsMouvementsRouteImport } from './routes/produits.mouvements'
import { Route as ProduitsProduitIdRouteImport } from './routes/produits.$produitId'
import { Route as MobileConnexionRouteImport } from './routes/mobile.connexion'
import { Route as InventaireHistoriqueRouteImport } from './routes/inventaire.historique'
import { Route as InventaireAnalyseRouteImport } from './routes/inventaire.analyse'
import { Route as InventaireInventaireIdRouteImport } from './routes/inventaire.$inventaireId'
import { Route as FournisseursApprovisionnementRouteImport } from './routes/fournisseurs.approvisionnement'
import { Route as FournisseursAnalyseRouteImport } from './routes/fournisseurs.analyse'
import { Route as FournisseursFournisseurIdRouteImport } from './routes/fournisseurs.$fournisseurId'
import { Route as EntreesStockHistoriqueRouteImport } from './routes/entrees-stock.historique'
import { Route as EntreesStockEntreeIdRouteImport } from './routes/entrees-stock.$entreeId'
import { Route as EmployesPresenceRouteImport } from './routes/employes.presence'
import { Route as EmployesPermissionsRouteImport } from './routes/employes.permissions'
import { Route as EmployesPerformanceRouteImport } from './routes/employes.performance'
import { Route as EmployesJournalRouteImport } from './routes/employes.journal'
import { Route as EmployesCongesRouteImport } from './routes/employes.conges'
import { Route as EmployesEmployeIdRouteImport } from './routes/employes.$employeId'
import { Route as DepensesTresorerieRouteImport } from './routes/depenses.tresorerie'
import { Route as DepensesPrevisionsRouteImport } from './routes/depenses.previsions'
import { Route as DepensesCreancesRouteImport } from './routes/depenses.creances'
import { Route as DepensesChargesRouteImport } from './routes/depenses.charges'
import { Route as DepensesAnalyseRouteImport } from './routes/depenses.analyse'
import { Route as ClientsVipRouteImport } from './routes/clients.vip'
import { Route as ClientsStatistiquesRouteImport } from './routes/clients.statistiques'
import { Route as ClientsAnalyseRouteImport } from './routes/clients.analyse'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as FournisseursCommandesIndexRouteImport } from './routes/fournisseurs.commandes.index'
import { Route as FournisseursCommandesCommandeIdRouteImport } from './routes/fournisseurs.commandes.$commandeId'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SortiesStockRoute = SortiesStockRouteImport.update({
  id: '/sorties-stock',
  path: '/sorties-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalairesRoute = SalairesRouteImport.update({
  id: '/salaires',
  path: '/salaires',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreesStockRoute = EntreesStockRouteImport.update({
  id: '/entrees-stock',
  path: '/entrees-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesIndexRoute = VentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VentesRoute,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduitsRoute,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const InventaireIndexRoute = InventaireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventaireRoute,
} as any)
const FournisseursIndexRoute = FournisseursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FournisseursRoute,
} as any)
const EntreesStockIndexRoute = EntreesStockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntreesStockRoute,
} as any)
const EmployesIndexRoute = EmployesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployesRoute,
} as any)
const DepensesIndexRoute = DepensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepensesRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const VentesRetoursRoute = VentesRetoursRouteImport.update({
  id: '/retours',
  path: '/retours',
  getParentRoute: () => VentesRoute,
} as any)
const VentesHistoriqueRoute = VentesHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => VentesRoute,
} as any)
const ProduitsMouvementsRoute = ProduitsMouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => ProduitsRoute,
} as any)
const ProduitsProduitIdRoute = ProduitsProduitIdRouteImport.update({
  id: '/$produitId',
  path: '/$produitId',
  getParentRoute: () => ProduitsRoute,
} as any)
const MobileConnexionRoute = MobileConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => MobileRoute,
} as any)
const InventaireHistoriqueRoute = InventaireHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => InventaireRoute,
} as any)
const InventaireAnalyseRoute = InventaireAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => InventaireRoute,
} as any)
const InventaireInventaireIdRoute = InventaireInventaireIdRouteImport.update({
  id: '/$inventaireId',
  path: '/$inventaireId',
  getParentRoute: () => InventaireRoute,
} as any)
const FournisseursApprovisionnementRoute =
  FournisseursApprovisionnementRouteImport.update({
    id: '/approvisionnement',
    path: '/approvisionnement',
    getParentRoute: () => FournisseursRoute,
  } as any)
const FournisseursAnalyseRoute = FournisseursAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => FournisseursRoute,
} as any)
const FournisseursFournisseurIdRoute =
  FournisseursFournisseurIdRouteImport.update({
    id: '/$fournisseurId',
    path: '/$fournisseurId',
    getParentRoute: () => FournisseursRoute,
  } as any)
const EntreesStockHistoriqueRoute = EntreesStockHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => EntreesStockRoute,
} as any)
const EntreesStockEntreeIdRoute = EntreesStockEntreeIdRouteImport.update({
  id: '/$entreeId',
  path: '/$entreeId',
  getParentRoute: () => EntreesStockRoute,
} as any)
const EmployesPresenceRoute = EmployesPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => EmployesRoute,
} as any)
const EmployesPermissionsRoute = EmployesPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => EmployesRoute,
} as any)
const EmployesPerformanceRoute = EmployesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => EmployesRoute,
} as any)
const EmployesJournalRoute = EmployesJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => EmployesRoute,
} as any)
const EmployesCongesRoute = EmployesCongesRouteImport.update({
  id: '/conges',
  path: '/conges',
  getParentRoute: () => EmployesRoute,
} as any)
const EmployesEmployeIdRoute = EmployesEmployeIdRouteImport.update({
  id: '/$employeId',
  path: '/$employeId',
  getParentRoute: () => EmployesRoute,
} as any)
const DepensesTresorerieRoute = DepensesTresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => DepensesRoute,
} as any)
const DepensesPrevisionsRoute = DepensesPrevisionsRouteImport.update({
  id: '/previsions',
  path: '/previsions',
  getParentRoute: () => DepensesRoute,
} as any)
const DepensesCreancesRoute = DepensesCreancesRouteImport.update({
  id: '/creances',
  path: '/creances',
  getParentRoute: () => DepensesRoute,
} as any)
const DepensesChargesRoute = DepensesChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => DepensesRoute,
} as any)
const DepensesAnalyseRoute = DepensesAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => DepensesRoute,
} as any)
const ClientsVipRoute = ClientsVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsStatistiquesRoute = ClientsStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsAnalyseRoute = ClientsAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const FournisseursCommandesIndexRoute =
  FournisseursCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => FournisseursRoute,
  } as any)
const FournisseursCommandesCommandeIdRoute =
  FournisseursCommandesCommandeIdRouteImport.update({
    id: '/commandes/$commandeId',
    path: '/commandes/$commandeId',
    getParentRoute: () => FournisseursRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/depenses': typeof DepensesRouteWithChildren
  '/employes': typeof EmployesRouteWithChildren
  '/entrees-stock': typeof EntreesStockRouteWithChildren
  '/fournisseurs': typeof FournisseursRouteWithChildren
  '/inventaire': typeof InventaireRouteWithChildren
  '/mobile': typeof MobileRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/ventes': typeof VentesRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/analyse': typeof ClientsAnalyseRoute
  '/clients/statistiques': typeof ClientsStatistiquesRoute
  '/clients/vip': typeof ClientsVipRoute
  '/depenses/analyse': typeof DepensesAnalyseRoute
  '/depenses/charges': typeof DepensesChargesRoute
  '/depenses/creances': typeof DepensesCreancesRoute
  '/depenses/previsions': typeof DepensesPrevisionsRoute
  '/depenses/tresorerie': typeof DepensesTresorerieRoute
  '/employes/$employeId': typeof EmployesEmployeIdRoute
  '/employes/conges': typeof EmployesCongesRoute
  '/employes/journal': typeof EmployesJournalRoute
  '/employes/performance': typeof EmployesPerformanceRoute
  '/employes/permissions': typeof EmployesPermissionsRoute
  '/employes/presence': typeof EmployesPresenceRoute
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs/analyse': typeof FournisseursAnalyseRoute
  '/fournisseurs/approvisionnement': typeof FournisseursApprovisionnementRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/mobile/connexion': typeof MobileConnexionRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/clients/': typeof ClientsIndexRoute
  '/depenses/': typeof DepensesIndexRoute
  '/employes/': typeof EmployesIndexRoute
  '/entrees-stock/': typeof EntreesStockIndexRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
  '/inventaire/': typeof InventaireIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/ventes/': typeof VentesIndexRoute
  '/fournisseurs/commandes/$commandeId': typeof FournisseursCommandesCommandeIdRoute
  '/fournisseurs/commandes/': typeof FournisseursCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/analyse': typeof ClientsAnalyseRoute
  '/clients/statistiques': typeof ClientsStatistiquesRoute
  '/clients/vip': typeof ClientsVipRoute
  '/depenses/analyse': typeof DepensesAnalyseRoute
  '/depenses/charges': typeof DepensesChargesRoute
  '/depenses/creances': typeof DepensesCreancesRoute
  '/depenses/previsions': typeof DepensesPrevisionsRoute
  '/depenses/tresorerie': typeof DepensesTresorerieRoute
  '/employes/$employeId': typeof EmployesEmployeIdRoute
  '/employes/conges': typeof EmployesCongesRoute
  '/employes/journal': typeof EmployesJournalRoute
  '/employes/performance': typeof EmployesPerformanceRoute
  '/employes/permissions': typeof EmployesPermissionsRoute
  '/employes/presence': typeof EmployesPresenceRoute
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs/analyse': typeof FournisseursAnalyseRoute
  '/fournisseurs/approvisionnement': typeof FournisseursApprovisionnementRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/mobile/connexion': typeof MobileConnexionRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/clients': typeof ClientsIndexRoute
  '/depenses': typeof DepensesIndexRoute
  '/employes': typeof EmployesIndexRoute
  '/entrees-stock': typeof EntreesStockIndexRoute
  '/fournisseurs': typeof FournisseursIndexRoute
  '/inventaire': typeof InventaireIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/ventes': typeof VentesIndexRoute
  '/fournisseurs/commandes/$commandeId': typeof FournisseursCommandesCommandeIdRoute
  '/fournisseurs/commandes': typeof FournisseursCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/depenses': typeof DepensesRouteWithChildren
  '/employes': typeof EmployesRouteWithChildren
  '/entrees-stock': typeof EntreesStockRouteWithChildren
  '/fournisseurs': typeof FournisseursRouteWithChildren
  '/inventaire': typeof InventaireRouteWithChildren
  '/mobile': typeof MobileRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/ventes': typeof VentesRouteWithChildren
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/analyse': typeof ClientsAnalyseRoute
  '/clients/statistiques': typeof ClientsStatistiquesRoute
  '/clients/vip': typeof ClientsVipRoute
  '/depenses/analyse': typeof DepensesAnalyseRoute
  '/depenses/charges': typeof DepensesChargesRoute
  '/depenses/creances': typeof DepensesCreancesRoute
  '/depenses/previsions': typeof DepensesPrevisionsRoute
  '/depenses/tresorerie': typeof DepensesTresorerieRoute
  '/employes/$employeId': typeof EmployesEmployeIdRoute
  '/employes/conges': typeof EmployesCongesRoute
  '/employes/journal': typeof EmployesJournalRoute
  '/employes/performance': typeof EmployesPerformanceRoute
  '/employes/permissions': typeof EmployesPermissionsRoute
  '/employes/presence': typeof EmployesPresenceRoute
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs/analyse': typeof FournisseursAnalyseRoute
  '/fournisseurs/approvisionnement': typeof FournisseursApprovisionnementRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/mobile/connexion': typeof MobileConnexionRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/clients/': typeof ClientsIndexRoute
  '/depenses/': typeof DepensesIndexRoute
  '/employes/': typeof EmployesIndexRoute
  '/entrees-stock/': typeof EntreesStockIndexRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
  '/inventaire/': typeof InventaireIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/ventes/': typeof VentesIndexRoute
  '/fournisseurs/commandes/$commandeId': typeof FournisseursCommandesCommandeIdRoute
  '/fournisseurs/commandes/': typeof FournisseursCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/entrees-stock'
    | '/fournisseurs'
    | '/inventaire'
    | '/mobile'
    | '/notifications'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/ventes'
    | '/clients/$clientId'
    | '/clients/analyse'
    | '/clients/statistiques'
    | '/clients/vip'
    | '/depenses/analyse'
    | '/depenses/charges'
    | '/depenses/creances'
    | '/depenses/previsions'
    | '/depenses/tresorerie'
    | '/employes/$employeId'
    | '/employes/conges'
    | '/employes/journal'
    | '/employes/performance'
    | '/employes/permissions'
    | '/employes/presence'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs/analyse'
    | '/fournisseurs/approvisionnement'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/mobile/connexion'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/clients/'
    | '/depenses/'
    | '/employes/'
    | '/entrees-stock/'
    | '/fournisseurs/'
    | '/inventaire/'
    | '/mobile/'
    | '/produits/'
    | '/ventes/'
    | '/fournisseurs/commandes/$commandeId'
    | '/fournisseurs/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caisse'
    | '/categories'
    | '/notifications'
    | '/parametres'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/clients/$clientId'
    | '/clients/analyse'
    | '/clients/statistiques'
    | '/clients/vip'
    | '/depenses/analyse'
    | '/depenses/charges'
    | '/depenses/creances'
    | '/depenses/previsions'
    | '/depenses/tresorerie'
    | '/employes/$employeId'
    | '/employes/conges'
    | '/employes/journal'
    | '/employes/performance'
    | '/employes/permissions'
    | '/employes/presence'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs/analyse'
    | '/fournisseurs/approvisionnement'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/mobile/connexion'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/entrees-stock'
    | '/fournisseurs'
    | '/inventaire'
    | '/mobile'
    | '/produits'
    | '/ventes'
    | '/fournisseurs/commandes/$commandeId'
    | '/fournisseurs/commandes'
  id:
    | '__root__'
    | '/'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/entrees-stock'
    | '/fournisseurs'
    | '/inventaire'
    | '/mobile'
    | '/notifications'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/ventes'
    | '/clients/$clientId'
    | '/clients/analyse'
    | '/clients/statistiques'
    | '/clients/vip'
    | '/depenses/analyse'
    | '/depenses/charges'
    | '/depenses/creances'
    | '/depenses/previsions'
    | '/depenses/tresorerie'
    | '/employes/$employeId'
    | '/employes/conges'
    | '/employes/journal'
    | '/employes/performance'
    | '/employes/permissions'
    | '/employes/presence'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs/analyse'
    | '/fournisseurs/approvisionnement'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/mobile/connexion'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/clients/'
    | '/depenses/'
    | '/employes/'
    | '/entrees-stock/'
    | '/fournisseurs/'
    | '/inventaire/'
    | '/mobile/'
    | '/produits/'
    | '/ventes/'
    | '/fournisseurs/commandes/$commandeId'
    | '/fournisseurs/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaisseRoute: typeof CaisseRoute
  CategoriesRoute: typeof CategoriesRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DepensesRoute: typeof DepensesRouteWithChildren
  EmployesRoute: typeof EmployesRouteWithChildren
  EntreesStockRoute: typeof EntreesStockRouteWithChildren
  FournisseursRoute: typeof FournisseursRouteWithChildren
  InventaireRoute: typeof InventaireRouteWithChildren
  MobileRoute: typeof MobileRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  RapportsRoute: typeof RapportsRoute
  SalairesRoute: typeof SalairesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SortiesStockRoute: typeof SortiesStockRoute
  StatistiquesRoute: typeof StatistiquesRoute
  VentesRoute: typeof VentesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorties-stock': {
      id: '/sorties-stock'
      path: '/sorties-stock'
      fullPath: '/sorties-stock'
      preLoaderRoute: typeof SortiesStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaires': {
      id: '/salaires'
      path: '/salaires'
      fullPath: '/salaires'
      preLoaderRoute: typeof SalairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrees-stock': {
      id: '/entrees-stock'
      path: '/entrees-stock'
      fullPath: '/entrees-stock'
      preLoaderRoute: typeof EntreesStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes/': {
      id: '/ventes/'
      path: '/'
      fullPath: '/ventes/'
      preLoaderRoute: typeof VentesIndexRouteImport
      parentRoute: typeof VentesRoute
    }
    '/produits/': {
      id: '/produits/'
      path: '/'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/inventaire/': {
      id: '/inventaire/'
      path: '/'
      fullPath: '/inventaire/'
      preLoaderRoute: typeof InventaireIndexRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/fournisseurs/': {
      id: '/fournisseurs/'
      path: '/'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof FournisseursIndexRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/entrees-stock/': {
      id: '/entrees-stock/'
      path: '/'
      fullPath: '/entrees-stock/'
      preLoaderRoute: typeof EntreesStockIndexRouteImport
      parentRoute: typeof EntreesStockRoute
    }
    '/employes/': {
      id: '/employes/'
      path: '/'
      fullPath: '/employes/'
      preLoaderRoute: typeof EmployesIndexRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/depenses/': {
      id: '/depenses/'
      path: '/'
      fullPath: '/depenses/'
      preLoaderRoute: typeof DepensesIndexRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/ventes/retours': {
      id: '/ventes/retours'
      path: '/retours'
      fullPath: '/ventes/retours'
      preLoaderRoute: typeof VentesRetoursRouteImport
      parentRoute: typeof VentesRoute
    }
    '/ventes/historique': {
      id: '/ventes/historique'
      path: '/historique'
      fullPath: '/ventes/historique'
      preLoaderRoute: typeof VentesHistoriqueRouteImport
      parentRoute: typeof VentesRoute
    }
    '/produits/mouvements': {
      id: '/produits/mouvements'
      path: '/mouvements'
      fullPath: '/produits/mouvements'
      preLoaderRoute: typeof ProduitsMouvementsRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/produits/$produitId': {
      id: '/produits/$produitId'
      path: '/$produitId'
      fullPath: '/produits/$produitId'
      preLoaderRoute: typeof ProduitsProduitIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/mobile/connexion': {
      id: '/mobile/connexion'
      path: '/connexion'
      fullPath: '/mobile/connexion'
      preLoaderRoute: typeof MobileConnexionRouteImport
      parentRoute: typeof MobileRoute
    }
    '/inventaire/historique': {
      id: '/inventaire/historique'
      path: '/historique'
      fullPath: '/inventaire/historique'
      preLoaderRoute: typeof InventaireHistoriqueRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/inventaire/analyse': {
      id: '/inventaire/analyse'
      path: '/analyse'
      fullPath: '/inventaire/analyse'
      preLoaderRoute: typeof InventaireAnalyseRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/inventaire/$inventaireId': {
      id: '/inventaire/$inventaireId'
      path: '/$inventaireId'
      fullPath: '/inventaire/$inventaireId'
      preLoaderRoute: typeof InventaireInventaireIdRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/fournisseurs/approvisionnement': {
      id: '/fournisseurs/approvisionnement'
      path: '/approvisionnement'
      fullPath: '/fournisseurs/approvisionnement'
      preLoaderRoute: typeof FournisseursApprovisionnementRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/fournisseurs/analyse': {
      id: '/fournisseurs/analyse'
      path: '/analyse'
      fullPath: '/fournisseurs/analyse'
      preLoaderRoute: typeof FournisseursAnalyseRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/fournisseurs/$fournisseurId': {
      id: '/fournisseurs/$fournisseurId'
      path: '/$fournisseurId'
      fullPath: '/fournisseurs/$fournisseurId'
      preLoaderRoute: typeof FournisseursFournisseurIdRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/entrees-stock/historique': {
      id: '/entrees-stock/historique'
      path: '/historique'
      fullPath: '/entrees-stock/historique'
      preLoaderRoute: typeof EntreesStockHistoriqueRouteImport
      parentRoute: typeof EntreesStockRoute
    }
    '/entrees-stock/$entreeId': {
      id: '/entrees-stock/$entreeId'
      path: '/$entreeId'
      fullPath: '/entrees-stock/$entreeId'
      preLoaderRoute: typeof EntreesStockEntreeIdRouteImport
      parentRoute: typeof EntreesStockRoute
    }
    '/employes/presence': {
      id: '/employes/presence'
      path: '/presence'
      fullPath: '/employes/presence'
      preLoaderRoute: typeof EmployesPresenceRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/employes/permissions': {
      id: '/employes/permissions'
      path: '/permissions'
      fullPath: '/employes/permissions'
      preLoaderRoute: typeof EmployesPermissionsRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/employes/performance': {
      id: '/employes/performance'
      path: '/performance'
      fullPath: '/employes/performance'
      preLoaderRoute: typeof EmployesPerformanceRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/employes/journal': {
      id: '/employes/journal'
      path: '/journal'
      fullPath: '/employes/journal'
      preLoaderRoute: typeof EmployesJournalRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/employes/conges': {
      id: '/employes/conges'
      path: '/conges'
      fullPath: '/employes/conges'
      preLoaderRoute: typeof EmployesCongesRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/employes/$employeId': {
      id: '/employes/$employeId'
      path: '/$employeId'
      fullPath: '/employes/$employeId'
      preLoaderRoute: typeof EmployesEmployeIdRouteImport
      parentRoute: typeof EmployesRoute
    }
    '/depenses/tresorerie': {
      id: '/depenses/tresorerie'
      path: '/tresorerie'
      fullPath: '/depenses/tresorerie'
      preLoaderRoute: typeof DepensesTresorerieRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/depenses/previsions': {
      id: '/depenses/previsions'
      path: '/previsions'
      fullPath: '/depenses/previsions'
      preLoaderRoute: typeof DepensesPrevisionsRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/depenses/creances': {
      id: '/depenses/creances'
      path: '/creances'
      fullPath: '/depenses/creances'
      preLoaderRoute: typeof DepensesCreancesRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/depenses/charges': {
      id: '/depenses/charges'
      path: '/charges'
      fullPath: '/depenses/charges'
      preLoaderRoute: typeof DepensesChargesRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/depenses/analyse': {
      id: '/depenses/analyse'
      path: '/analyse'
      fullPath: '/depenses/analyse'
      preLoaderRoute: typeof DepensesAnalyseRouteImport
      parentRoute: typeof DepensesRoute
    }
    '/clients/vip': {
      id: '/clients/vip'
      path: '/vip'
      fullPath: '/clients/vip'
      preLoaderRoute: typeof ClientsVipRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/statistiques': {
      id: '/clients/statistiques'
      path: '/statistiques'
      fullPath: '/clients/statistiques'
      preLoaderRoute: typeof ClientsStatistiquesRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/analyse': {
      id: '/clients/analyse'
      path: '/analyse'
      fullPath: '/clients/analyse'
      preLoaderRoute: typeof ClientsAnalyseRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/fournisseurs/commandes/': {
      id: '/fournisseurs/commandes/'
      path: '/commandes'
      fullPath: '/fournisseurs/commandes/'
      preLoaderRoute: typeof FournisseursCommandesIndexRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/fournisseurs/commandes/$commandeId': {
      id: '/fournisseurs/commandes/$commandeId'
      path: '/commandes/$commandeId'
      fullPath: '/fournisseurs/commandes/$commandeId'
      preLoaderRoute: typeof FournisseursCommandesCommandeIdRouteImport
      parentRoute: typeof FournisseursRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsAnalyseRoute: typeof ClientsAnalyseRoute
  ClientsStatistiquesRoute: typeof ClientsStatistiquesRoute
  ClientsVipRoute: typeof ClientsVipRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsAnalyseRoute: ClientsAnalyseRoute,
  ClientsStatistiquesRoute: ClientsStatistiquesRoute,
  ClientsVipRoute: ClientsVipRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DepensesRouteChildren {
  DepensesAnalyseRoute: typeof DepensesAnalyseRoute
  DepensesChargesRoute: typeof DepensesChargesRoute
  DepensesCreancesRoute: typeof DepensesCreancesRoute
  DepensesPrevisionsRoute: typeof DepensesPrevisionsRoute
  DepensesTresorerieRoute: typeof DepensesTresorerieRoute
  DepensesIndexRoute: typeof DepensesIndexRoute
}

const DepensesRouteChildren: DepensesRouteChildren = {
  DepensesAnalyseRoute: DepensesAnalyseRoute,
  DepensesChargesRoute: DepensesChargesRoute,
  DepensesCreancesRoute: DepensesCreancesRoute,
  DepensesPrevisionsRoute: DepensesPrevisionsRoute,
  DepensesTresorerieRoute: DepensesTresorerieRoute,
  DepensesIndexRoute: DepensesIndexRoute,
}

const DepensesRouteWithChildren = DepensesRoute._addFileChildren(
  DepensesRouteChildren,
)

interface EmployesRouteChildren {
  EmployesEmployeIdRoute: typeof EmployesEmployeIdRoute
  EmployesCongesRoute: typeof EmployesCongesRoute
  EmployesJournalRoute: typeof EmployesJournalRoute
  EmployesPerformanceRoute: typeof EmployesPerformanceRoute
  EmployesPermissionsRoute: typeof EmployesPermissionsRoute
  EmployesPresenceRoute: typeof EmployesPresenceRoute
  EmployesIndexRoute: typeof EmployesIndexRoute
}

const EmployesRouteChildren: EmployesRouteChildren = {
  EmployesEmployeIdRoute: EmployesEmployeIdRoute,
  EmployesCongesRoute: EmployesCongesRoute,
  EmployesJournalRoute: EmployesJournalRoute,
  EmployesPerformanceRoute: EmployesPerformanceRoute,
  EmployesPermissionsRoute: EmployesPermissionsRoute,
  EmployesPresenceRoute: EmployesPresenceRoute,
  EmployesIndexRoute: EmployesIndexRoute,
}

const EmployesRouteWithChildren = EmployesRoute._addFileChildren(
  EmployesRouteChildren,
)

interface EntreesStockRouteChildren {
  EntreesStockEntreeIdRoute: typeof EntreesStockEntreeIdRoute
  EntreesStockHistoriqueRoute: typeof EntreesStockHistoriqueRoute
  EntreesStockIndexRoute: typeof EntreesStockIndexRoute
}

const EntreesStockRouteChildren: EntreesStockRouteChildren = {
  EntreesStockEntreeIdRoute: EntreesStockEntreeIdRoute,
  EntreesStockHistoriqueRoute: EntreesStockHistoriqueRoute,
  EntreesStockIndexRoute: EntreesStockIndexRoute,
}

const EntreesStockRouteWithChildren = EntreesStockRoute._addFileChildren(
  EntreesStockRouteChildren,
)

interface FournisseursRouteChildren {
  FournisseursFournisseurIdRoute: typeof FournisseursFournisseurIdRoute
  FournisseursAnalyseRoute: typeof FournisseursAnalyseRoute
  FournisseursApprovisionnementRoute: typeof FournisseursApprovisionnementRoute
  FournisseursIndexRoute: typeof FournisseursIndexRoute
  FournisseursCommandesCommandeIdRoute: typeof FournisseursCommandesCommandeIdRoute
  FournisseursCommandesIndexRoute: typeof FournisseursCommandesIndexRoute
}

const FournisseursRouteChildren: FournisseursRouteChildren = {
  FournisseursFournisseurIdRoute: FournisseursFournisseurIdRoute,
  FournisseursAnalyseRoute: FournisseursAnalyseRoute,
  FournisseursApprovisionnementRoute: FournisseursApprovisionnementRoute,
  FournisseursIndexRoute: FournisseursIndexRoute,
  FournisseursCommandesCommandeIdRoute: FournisseursCommandesCommandeIdRoute,
  FournisseursCommandesIndexRoute: FournisseursCommandesIndexRoute,
}

const FournisseursRouteWithChildren = FournisseursRoute._addFileChildren(
  FournisseursRouteChildren,
)

interface InventaireRouteChildren {
  InventaireInventaireIdRoute: typeof InventaireInventaireIdRoute
  InventaireAnalyseRoute: typeof InventaireAnalyseRoute
  InventaireHistoriqueRoute: typeof InventaireHistoriqueRoute
  InventaireIndexRoute: typeof InventaireIndexRoute
}

const InventaireRouteChildren: InventaireRouteChildren = {
  InventaireInventaireIdRoute: InventaireInventaireIdRoute,
  InventaireAnalyseRoute: InventaireAnalyseRoute,
  InventaireHistoriqueRoute: InventaireHistoriqueRoute,
  InventaireIndexRoute: InventaireIndexRoute,
}

const InventaireRouteWithChildren = InventaireRoute._addFileChildren(
  InventaireRouteChildren,
)

interface MobileRouteChildren {
  MobileConnexionRoute: typeof MobileConnexionRoute
  MobileIndexRoute: typeof MobileIndexRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileConnexionRoute: MobileConnexionRoute,
  MobileIndexRoute: MobileIndexRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface ProduitsRouteChildren {
  ProduitsProduitIdRoute: typeof ProduitsProduitIdRoute
  ProduitsMouvementsRoute: typeof ProduitsMouvementsRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsProduitIdRoute: ProduitsProduitIdRoute,
  ProduitsMouvementsRoute: ProduitsMouvementsRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

interface VentesRouteChildren {
  VentesHistoriqueRoute: typeof VentesHistoriqueRoute
  VentesRetoursRoute: typeof VentesRetoursRoute
  VentesIndexRoute: typeof VentesIndexRoute
}

const VentesRouteChildren: VentesRouteChildren = {
  VentesHistoriqueRoute: VentesHistoriqueRoute,
  VentesRetoursRoute: VentesRetoursRoute,
  VentesIndexRoute: VentesIndexRoute,
}

const VentesRouteWithChildren =
  VentesRoute._addFileChildren(VentesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaisseRoute: CaisseRoute,
  CategoriesRoute: CategoriesRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DepensesRoute: DepensesRouteWithChildren,
  EmployesRoute: EmployesRouteWithChildren,
  EntreesStockRoute: EntreesStockRouteWithChildren,
  FournisseursRoute: FournisseursRouteWithChildren,
  InventaireRoute: InventaireRouteWithChildren,
  MobileRoute: MobileRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  RapportsRoute: RapportsRoute,
  SalairesRoute: SalairesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SortiesStockRoute: SortiesStockRoute,
  StatistiquesRoute: StatistiquesRoute,
  VentesRoute: VentesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
