/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as SortiesStockRouteImport } from './routes/sorties-stock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalairesRouteImport } from './routes/salaires'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as EntreesStockRouteImport } from './routes/entrees-stock'
import { Route as EmployesRouteImport } from './routes/employes'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VentesIndexRouteImport } from './routes/ventes.index'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as InventaireIndexRouteImport } from './routes/inventaire.index'
import { Route as EntreesStockIndexRouteImport } from './routes/entrees-stock.index'
import { Route as VentesRetoursRouteImport } from './routes/ventes.retours'
import { Route as VentesHistoriqueRouteImport } from './routes/ventes.historique'
import { Route as ProduitsMouvementsRouteImport } from './routes/produits.mouvements'
import { Route as ProduitsProduitIdRouteImport } from './routes/produits.$produitId'
import { Route as InventaireHistoriqueRouteImport } from './routes/inventaire.historique'
import { Route as InventaireAnalyseRouteImport } from './routes/inventaire.analyse'
import { Route as InventaireInventaireIdRouteImport } from './routes/inventaire.$inventaireId'
import { Route as EntreesStockHistoriqueRouteImport } from './routes/entrees-stock.historique'
import { Route as EntreesStockEntreeIdRouteImport } from './routes/entrees-stock.$entreeId'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const SortiesStockRoute = SortiesStockRouteImport.update({
  id: '/sorties-stock',
  path: '/sorties-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalairesRoute = SalairesRouteImport.update({
  id: '/salaires',
  path: '/salaires',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreesStockRoute = EntreesStockRouteImport.update({
  id: '/entrees-stock',
  path: '/entrees-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployesRoute = EmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentesIndexRoute = VentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VentesRoute,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduitsRoute,
} as any)
const InventaireIndexRoute = InventaireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventaireRoute,
} as any)
const EntreesStockIndexRoute = EntreesStockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntreesStockRoute,
} as any)
const VentesRetoursRoute = VentesRetoursRouteImport.update({
  id: '/retours',
  path: '/retours',
  getParentRoute: () => VentesRoute,
} as any)
const VentesHistoriqueRoute = VentesHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => VentesRoute,
} as any)
const ProduitsMouvementsRoute = ProduitsMouvementsRouteImport.update({
  id: '/mouvements',
  path: '/mouvements',
  getParentRoute: () => ProduitsRoute,
} as any)
const ProduitsProduitIdRoute = ProduitsProduitIdRouteImport.update({
  id: '/$produitId',
  path: '/$produitId',
  getParentRoute: () => ProduitsRoute,
} as any)
const InventaireHistoriqueRoute = InventaireHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => InventaireRoute,
} as any)
const InventaireAnalyseRoute = InventaireAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => InventaireRoute,
} as any)
const InventaireInventaireIdRoute = InventaireInventaireIdRouteImport.update({
  id: '/$inventaireId',
  path: '/$inventaireId',
  getParentRoute: () => InventaireRoute,
} as any)
const EntreesStockHistoriqueRoute = EntreesStockHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => EntreesStockRoute,
} as any)
const EntreesStockEntreeIdRoute = EntreesStockEntreeIdRouteImport.update({
  id: '/$entreeId',
  path: '/$entreeId',
  getParentRoute: () => EntreesStockRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/employes': typeof EmployesRoute
  '/entrees-stock': typeof EntreesStockRouteWithChildren
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/ventes': typeof VentesRouteWithChildren
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/entrees-stock/': typeof EntreesStockIndexRoute
  '/inventaire/': typeof InventaireIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/ventes/': typeof VentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/employes': typeof EmployesRoute
  '/fournisseurs': typeof FournisseursRoute
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/entrees-stock': typeof EntreesStockIndexRoute
  '/inventaire': typeof InventaireIndexRoute
  '/produits': typeof ProduitsIndexRoute
  '/ventes': typeof VentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/depenses': typeof DepensesRoute
  '/employes': typeof EmployesRoute
  '/entrees-stock': typeof EntreesStockRouteWithChildren
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRouteWithChildren
  '/rapports': typeof RapportsRoute
  '/salaires': typeof SalairesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sorties-stock': typeof SortiesStockRoute
  '/statistiques': typeof StatistiquesRoute
  '/ventes': typeof VentesRouteWithChildren
  '/entrees-stock/$entreeId': typeof EntreesStockEntreeIdRoute
  '/entrees-stock/historique': typeof EntreesStockHistoriqueRoute
  '/inventaire/$inventaireId': typeof InventaireInventaireIdRoute
  '/inventaire/analyse': typeof InventaireAnalyseRoute
  '/inventaire/historique': typeof InventaireHistoriqueRoute
  '/produits/$produitId': typeof ProduitsProduitIdRoute
  '/produits/mouvements': typeof ProduitsMouvementsRoute
  '/ventes/historique': typeof VentesHistoriqueRoute
  '/ventes/retours': typeof VentesRetoursRoute
  '/entrees-stock/': typeof EntreesStockIndexRoute
  '/inventaire/': typeof InventaireIndexRoute
  '/produits/': typeof ProduitsIndexRoute
  '/ventes/': typeof VentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/entrees-stock'
    | '/fournisseurs'
    | '/inventaire'
    | '/notifications'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/ventes'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/entrees-stock/'
    | '/inventaire/'
    | '/produits/'
    | '/ventes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/fournisseurs'
    | '/notifications'
    | '/parametres'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/entrees-stock'
    | '/inventaire'
    | '/produits'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/depenses'
    | '/employes'
    | '/entrees-stock'
    | '/fournisseurs'
    | '/inventaire'
    | '/notifications'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/salaires'
    | '/sitemap.xml'
    | '/sorties-stock'
    | '/statistiques'
    | '/ventes'
    | '/entrees-stock/$entreeId'
    | '/entrees-stock/historique'
    | '/inventaire/$inventaireId'
    | '/inventaire/analyse'
    | '/inventaire/historique'
    | '/produits/$produitId'
    | '/produits/mouvements'
    | '/ventes/historique'
    | '/ventes/retours'
    | '/entrees-stock/'
    | '/inventaire/'
    | '/produits/'
    | '/ventes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaisseRoute: typeof CaisseRoute
  CategoriesRoute: typeof CategoriesRoute
  ClientsRoute: typeof ClientsRoute
  DepensesRoute: typeof DepensesRoute
  EmployesRoute: typeof EmployesRoute
  EntreesStockRoute: typeof EntreesStockRouteWithChildren
  FournisseursRoute: typeof FournisseursRoute
  InventaireRoute: typeof InventaireRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRouteWithChildren
  RapportsRoute: typeof RapportsRoute
  SalairesRoute: typeof SalairesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SortiesStockRoute: typeof SortiesStockRoute
  StatistiquesRoute: typeof StatistiquesRoute
  VentesRoute: typeof VentesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorties-stock': {
      id: '/sorties-stock'
      path: '/sorties-stock'
      fullPath: '/sorties-stock'
      preLoaderRoute: typeof SortiesStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaires': {
      id: '/salaires'
      path: '/salaires'
      fullPath: '/salaires'
      preLoaderRoute: typeof SalairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrees-stock': {
      id: '/entrees-stock'
      path: '/entrees-stock'
      fullPath: '/entrees-stock'
      preLoaderRoute: typeof EntreesStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employes': {
      id: '/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof EmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventes/': {
      id: '/ventes/'
      path: '/'
      fullPath: '/ventes/'
      preLoaderRoute: typeof VentesIndexRouteImport
      parentRoute: typeof VentesRoute
    }
    '/produits/': {
      id: '/produits/'
      path: '/'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/inventaire/': {
      id: '/inventaire/'
      path: '/'
      fullPath: '/inventaire/'
      preLoaderRoute: typeof InventaireIndexRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/entrees-stock/': {
      id: '/entrees-stock/'
      path: '/'
      fullPath: '/entrees-stock/'
      preLoaderRoute: typeof EntreesStockIndexRouteImport
      parentRoute: typeof EntreesStockRoute
    }
    '/ventes/retours': {
      id: '/ventes/retours'
      path: '/retours'
      fullPath: '/ventes/retours'
      preLoaderRoute: typeof VentesRetoursRouteImport
      parentRoute: typeof VentesRoute
    }
    '/ventes/historique': {
      id: '/ventes/historique'
      path: '/historique'
      fullPath: '/ventes/historique'
      preLoaderRoute: typeof VentesHistoriqueRouteImport
      parentRoute: typeof VentesRoute
    }
    '/produits/mouvements': {
      id: '/produits/mouvements'
      path: '/mouvements'
      fullPath: '/produits/mouvements'
      preLoaderRoute: typeof ProduitsMouvementsRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/produits/$produitId': {
      id: '/produits/$produitId'
      path: '/$produitId'
      fullPath: '/produits/$produitId'
      preLoaderRoute: typeof ProduitsProduitIdRouteImport
      parentRoute: typeof ProduitsRoute
    }
    '/inventaire/historique': {
      id: '/inventaire/historique'
      path: '/historique'
      fullPath: '/inventaire/historique'
      preLoaderRoute: typeof InventaireHistoriqueRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/inventaire/analyse': {
      id: '/inventaire/analyse'
      path: '/analyse'
      fullPath: '/inventaire/analyse'
      preLoaderRoute: typeof InventaireAnalyseRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/inventaire/$inventaireId': {
      id: '/inventaire/$inventaireId'
      path: '/$inventaireId'
      fullPath: '/inventaire/$inventaireId'
      preLoaderRoute: typeof InventaireInventaireIdRouteImport
      parentRoute: typeof InventaireRoute
    }
    '/entrees-stock/historique': {
      id: '/entrees-stock/historique'
      path: '/historique'
      fullPath: '/entrees-stock/historique'
      preLoaderRoute: typeof EntreesStockHistoriqueRouteImport
      parentRoute: typeof EntreesStockRoute
    }
    '/entrees-stock/$entreeId': {
      id: '/entrees-stock/$entreeId'
      path: '/$entreeId'
      fullPath: '/entrees-stock/$entreeId'
      preLoaderRoute: typeof EntreesStockEntreeIdRouteImport
      parentRoute: typeof EntreesStockRoute
    }
  }
}

interface EntreesStockRouteChildren {
  EntreesStockEntreeIdRoute: typeof EntreesStockEntreeIdRoute
  EntreesStockHistoriqueRoute: typeof EntreesStockHistoriqueRoute
  EntreesStockIndexRoute: typeof EntreesStockIndexRoute
}

const EntreesStockRouteChildren: EntreesStockRouteChildren = {
  EntreesStockEntreeIdRoute: EntreesStockEntreeIdRoute,
  EntreesStockHistoriqueRoute: EntreesStockHistoriqueRoute,
  EntreesStockIndexRoute: EntreesStockIndexRoute,
}

const EntreesStockRouteWithChildren = EntreesStockRoute._addFileChildren(
  EntreesStockRouteChildren,
)

interface InventaireRouteChildren {
  InventaireInventaireIdRoute: typeof InventaireInventaireIdRoute
  InventaireAnalyseRoute: typeof InventaireAnalyseRoute
  InventaireHistoriqueRoute: typeof InventaireHistoriqueRoute
  InventaireIndexRoute: typeof InventaireIndexRoute
}

const InventaireRouteChildren: InventaireRouteChildren = {
  InventaireInventaireIdRoute: InventaireInventaireIdRoute,
  InventaireAnalyseRoute: InventaireAnalyseRoute,
  InventaireHistoriqueRoute: InventaireHistoriqueRoute,
  InventaireIndexRoute: InventaireIndexRoute,
}

const InventaireRouteWithChildren = InventaireRoute._addFileChildren(
  InventaireRouteChildren,
)

interface ProduitsRouteChildren {
  ProduitsProduitIdRoute: typeof ProduitsProduitIdRoute
  ProduitsMouvementsRoute: typeof ProduitsMouvementsRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
}

const ProduitsRouteChildren: ProduitsRouteChildren = {
  ProduitsProduitIdRoute: ProduitsProduitIdRoute,
  ProduitsMouvementsRoute: ProduitsMouvementsRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
}

const ProduitsRouteWithChildren = ProduitsRoute._addFileChildren(
  ProduitsRouteChildren,
)

interface VentesRouteChildren {
  VentesHistoriqueRoute: typeof VentesHistoriqueRoute
  VentesRetoursRoute: typeof VentesRetoursRoute
  VentesIndexRoute: typeof VentesIndexRoute
}

const VentesRouteChildren: VentesRouteChildren = {
  VentesHistoriqueRoute: VentesHistoriqueRoute,
  VentesRetoursRoute: VentesRetoursRoute,
  VentesIndexRoute: VentesIndexRoute,
}

const VentesRouteWithChildren =
  VentesRoute._addFileChildren(VentesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaisseRoute: CaisseRoute,
  CategoriesRoute: CategoriesRoute,
  ClientsRoute: ClientsRoute,
  DepensesRoute: DepensesRoute,
  EmployesRoute: EmployesRoute,
  EntreesStockRoute: EntreesStockRouteWithChildren,
  FournisseursRoute: FournisseursRoute,
  InventaireRoute: InventaireRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRouteWithChildren,
  RapportsRoute: RapportsRoute,
  SalairesRoute: SalairesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SortiesStockRoute: SortiesStockRoute,
  StatistiquesRoute: StatistiquesRoute,
  VentesRoute: VentesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
