import type {
  EntreeAudit,
  Entreprise,
  InfosEntreprise,
  Magasin,
  ParametresFinanciers,
  ParametresStocks,
  ParametresVentes,
  Personnalisation,
  PolitiqueMotDePasse,
  PreferencesNotifications,
  Role,
  Sauvegarde,
  PlanificationSauvegarde,
  Session,
  Utilisateur,
} from "./types";

export const ENTREPRISE_COURANTE = "ENT-501";

const ilYA = (heures: number) => new Date(Date.now() - heures * 3_600_000).toISOString();
const ilYAJours = (jours: number) => new Date(Date.now() - jours * 86_400_000).toISOString();

export const infosEntrepriseDemo: InfosEntreprise = {
  logo: "",
  nom: "Bekaye Sora SARL",
  nomCommercial: "Bekaye Sora Business Manager",
  slogan: "501 – Révélez votre éclat.",
  adresse: "Avenue Kwamé N'Krumah, Ouagadougou, Burkina Faso",
  telephone: "+226 70 12 34 56",
  whatsapp: "+226 70 12 34 56",
  email: "contact@bekayesora.bf",
  siteWeb: "https://bekayesora.bf",
  identifiant: "IFU-00512345B",
  devise: "XOF",
  fuseauHoraire: "Africa/Ouagadougou (GMT+0)",
  langue: "fr",
  formatDate: "jj/mm/aaaa",
};

export const personnalisationDemo: Personnalisation = {
  couleurPrincipale: "#D62828",
  logoClair: "",
  logoSombre: "",
  favicon: "",
  theme: "clair",
  police: "Sora",
};

export const rolesDemo: Role[] = [
  {
    id: "ROLE-DIR",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Directeur",
    description: "Accès complet à l'ensemble des modules et de l'administration.",
    systeme: true,
    permissions: [
      "voir",
      "creer",
      "modifier",
      "supprimer",
      "exporter",
      "imprimer",
      "valider",
      "administrer",
    ],
  },
  {
    id: "ROLE-GER",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Gérant",
    description: "Pilotage quotidien du magasin, sans administration système.",
    systeme: true,
    permissions: ["voir", "creer", "modifier", "exporter", "imprimer", "valider"],
  },
  {
    id: "ROLE-CAI",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Caissier",
    description: "Encaissement et consultation du catalogue produits.",
    systeme: true,
    permissions: ["voir", "creer", "imprimer"],
  },
  {
    id: "ROLE-MAG",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Magasinier",
    description: "Réceptions, inventaires et mouvements de stock.",
    systeme: false,
    permissions: ["voir", "creer", "modifier", "imprimer"],
  },
];

export const utilisateursDemo: Utilisateur[] = [
  {
    id: "USR-001",
    entrepriseId: ENTREPRISE_COURANTE,
    magasinId: "MAG-01",
    nom: "Bekaye Sora",
    email: "bekaye@bekayesora.bf",
    telephone: "+226 70 12 34 56",
    roleId: "ROLE-DIR",
    statut: "actif",
    derniereConnexion: ilYA(1),
    creeLe: ilYAJours(420),
  },
  {
    id: "USR-002",
    entrepriseId: ENTREPRISE_COURANTE,
    magasinId: "MAG-01",
    nom: "Aminata Ouédraogo",
    email: "aminata@bekayesora.bf",
    telephone: "+226 76 88 21 09",
    roleId: "ROLE-GER",
    statut: "actif",
    derniereConnexion: ilYA(4),
    creeLe: ilYAJours(210),
  },
  {
    id: "USR-003",
    entrepriseId: ENTREPRISE_COURANTE,
    magasinId: "MAG-02",
    nom: "Ibrahim Traoré",
    email: "ibrahim@bekayesora.bf",
    telephone: "+226 65 44 12 77",
    roleId: "ROLE-CAI",
    statut: "actif",
    derniereConnexion: ilYA(26),
    creeLe: ilYAJours(120),
  },
  {
    id: "USR-004",
    entrepriseId: ENTREPRISE_COURANTE,
    magasinId: "MAG-02",
    nom: "Fatimata Zongo",
    email: "fatimata@bekayesora.bf",
    telephone: "+226 74 90 33 18",
    roleId: "ROLE-MAG",
    statut: "suspendu",
    derniereConnexion: ilYAJours(19),
    creeLe: ilYAJours(95),
  },
  {
    id: "USR-005",
    entrepriseId: ENTREPRISE_COURANTE,
    magasinId: null,
    nom: "Salif Kaboré",
    email: "salif@bekayesora.bf",
    telephone: "+226 78 55 41 02",
    roleId: "ROLE-CAI",
    statut: "invite",
    derniereConnexion: null,
    creeLe: ilYAJours(2),
  },
];

export const auditDemo: EntreeAudit[] = [
  {
    id: "AUD-001",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYA(1),
    utilisateur: "Bekaye Sora",
    action: "connexion",
    module: "Authentification",
    details: "Connexion réussie via biométrie mobile.",
    ip: "196.28.240.11",
    appareil: "iPhone 15 · iOS 18",
  },
  {
    id: "AUD-002",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYA(2),
    utilisateur: "Aminata Ouédraogo",
    action: "creation",
    module: "Ventes",
    details: "Facture FA-2041 créée (48 500 FCFA).",
    ip: "196.28.240.24",
    appareil: "Chrome · Windows 11",
  },
  {
    id: "AUD-003",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYA(5),
    utilisateur: "Ibrahim Traoré",
    action: "modification",
    module: "Produits",
    details: "Prix de vente du produit « Lait éclaircissant 501 » modifié.",
    ip: "196.28.240.31",
    appareil: "Chrome · Android 14",
  },
  {
    id: "AUD-004",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYA(9),
    utilisateur: "Inconnu",
    action: "connexion_echouee",
    module: "Authentification",
    details: "3 tentatives échouées pour fatimata@bekayesora.bf.",
    ip: "102.64.18.203",
    appareil: "Firefox · Linux",
  },
  {
    id: "AUD-005",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYA(14),
    utilisateur: "Fatimata Zongo",
    action: "acces_refuse",
    module: "Finances",
    details: "Tentative d'accès au module Trésorerie sans permission.",
    ip: "196.28.240.44",
    appareil: "Chrome · Windows 10",
  },
  {
    id: "AUD-006",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYAJours(1),
    utilisateur: "Bekaye Sora",
    action: "export",
    module: "Rapports",
    details: "Export PDF du rapport mensuel de direction.",
    ip: "196.28.240.11",
    appareil: "Safari · macOS",
  },
  {
    id: "AUD-007",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYAJours(2),
    utilisateur: "Aminata Ouédraogo",
    action: "suppression",
    module: "Fournisseurs",
    details: "Commande d'achat CA-0192 annulée puis supprimée.",
    ip: "196.28.240.24",
    appareil: "Chrome · Windows 11",
  },
  {
    id: "AUD-008",
    entrepriseId: ENTREPRISE_COURANTE,
    date: ilYAJours(3),
    utilisateur: "Ibrahim Traoré",
    action: "deconnexion",
    module: "Authentification",
    details: "Fermeture de session après clôture de caisse.",
    ip: "196.28.240.31",
    appareil: "Chrome · Android 14",
  },
];

export const sessionsDemo: Session[] = [
  {
    id: "SES-001",
    utilisateur: "Bekaye Sora",
    appareil: "Safari · macOS",
    ip: "196.28.240.11",
    localisation: "Ouagadougou, BF",
    debut: ilYA(1),
    courante: true,
  },
  {
    id: "SES-002",
    utilisateur: "Bekaye Sora",
    appareil: "iPhone 15 · Application mobile",
    ip: "196.28.240.12",
    localisation: "Ouagadougou, BF",
    debut: ilYA(6),
    courante: false,
  },
  {
    id: "SES-003",
    utilisateur: "Aminata Ouédraogo",
    appareil: "Chrome · Windows 11",
    ip: "196.28.240.24",
    localisation: "Bobo-Dioulasso, BF",
    debut: ilYA(3),
    courante: false,
  },
];

export const politiqueDemo: PolitiqueMotDePasse = {
  longueurMin: 10,
  majuscule: true,
  chiffre: true,
  special: false,
  expirationJours: 90,
  double_authentification: false,
};

export const sauvegardesDemo: Sauvegarde[] = [
  {
    id: "BCK-014",
    date: ilYA(3),
    taille: "18,4 Mo",
    type: "automatique",
    statut: "reussie",
    auteur: "Système",
  },
  {
    id: "BCK-013",
    date: ilYAJours(1),
    taille: "18,1 Mo",
    type: "automatique",
    statut: "reussie",
    auteur: "Système",
  },
  {
    id: "BCK-012",
    date: ilYAJours(2),
    taille: "17,9 Mo",
    type: "manuelle",
    statut: "reussie",
    auteur: "Bekaye Sora",
  },
  {
    id: "BCK-011",
    date: ilYAJours(3),
    taille: "—",
    type: "automatique",
    statut: "echouee",
    auteur: "Système",
  },
];

export const planificationDemo: PlanificationSauvegarde = {
  active: true,
  frequence: "quotidienne",
  heure: "02:00",
  retentionJours: 30,
};

export const notificationsDemo: PreferencesNotifications = {
  internes: true,
  email: true,
  whatsapp: false,
  push: true,
  emailDestinataire: "direction@bekayesora.bf",
};

export const magasinsDemo: Magasin[] = [
  {
    id: "MAG-01",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Boutique Centre-ville",
    adresse: "Avenue Kwamé N'Krumah, Ouagadougou",
    responsable: "Aminata Ouédraogo",
    telephone: "+226 70 12 34 56",
    actif: true,
    employes: 6,
    valeurStock: 8_450_000,
    caisseJour: 312_500,
  },
  {
    id: "MAG-02",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Dépôt Gounghin",
    adresse: "Rue 12.18, Gounghin, Ouagadougou",
    responsable: "Ibrahim Traoré",
    telephone: "+226 65 44 12 77",
    actif: true,
    employes: 4,
    valeurStock: 5_120_000,
    caisseJour: 147_000,
  },
  {
    id: "MAG-03",
    entrepriseId: ENTREPRISE_COURANTE,
    nom: "Point de vente Bobo",
    adresse: "Secteur 4, Bobo-Dioulasso",
    responsable: "Salif Kaboré",
    telephone: "+226 78 55 41 02",
    actif: false,
    employes: 2,
    valeurStock: 1_980_000,
    caisseJour: 0,
  },
];

export const entreprisesDemo: Entreprise[] = [
  {
    id: ENTREPRISE_COURANTE,
    nom: "Bekaye Sora SARL",
    logo: "",
    secteur: "Cosmétiques – Marque 501",
    pays: "Burkina Faso",
    plan: "Business",
    active: true,
    creeLe: ilYAJours(420),
  },
  {
    id: "ENT-KAD",
    nom: "Kadi Beauté",
    logo: "",
    secteur: "Distribution cosmétique",
    pays: "Côte d'Ivoire",
    plan: "Essentiel",
    active: false,
    creeLe: ilYAJours(90),
  },
];

export const parametresVentesDemo: ParametresVentes = {
  tvaActive: true,
  tauxTva: 18,
  remiseMaxPourcent: 15,
  prefixeFacture: "FA-",
  prochainNumero: 2042,
  conditionsPaiement: "Paiement comptant. Aucun échange après 7 jours.",
};

export const parametresStocksDemo: ParametresStocks = {
  stockMinimumDefaut: 10,
  gestionLots: true,
  datesPeremption: true,
  alerteExpirationJours: 60,
  inventaireAutomatique: "mensuel",
};

export const parametresFinanciersDemo: ParametresFinanciers = {
  devise: "XOF",
  categoriesDepenses: [
    "Loyer",
    "Salaires",
    "Transport",
    "Électricité",
    "Marketing",
    "Fournitures",
  ],
  objectifCaMensuel: 12_000_000,
  budgetDepensesMensuel: 4_500_000,
};
