import type {
  CommandeAchat,
  Fournisseur,
  NotificationFournisseur,
} from "./types";

const j = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const jPlus = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString();

export const fournisseursDemo: Fournisseur[] = [
  {
    id: "F-001",
    nom: "Cosmetic Import SARL",
    entreprise: "Cosmetic Import SARL",
    telephone: "+223 20 22 44 18",
    whatsapp: "+223 76 12 44 18",
    email: "contact@cosmetic-import.ml",
    adresse: "Zone industrielle, Rue 231, Porte 44",
    ville: "Bamako",
    pays: "Mali",
    contactPrincipal: "Moussa Traoré",
    conditionsPaiement: "Paiement à 30 jours",
    delaiLivraisonJours: 7,
    notes: "Partenaire historique pour les lotions et crèmes. Remise de 5 % dès 100 cartons.",
    logo: null,
    favori: true,
    actif: true,
    dateCreation: j(720),
  },
  {
    id: "F-002",
    nom: "Distribution Sahel",
    entreprise: "Distribution Sahel SA",
    telephone: "+223 21 33 08 76",
    whatsapp: "+223 70 33 08 76",
    email: "commandes@distribution-sahel.ml",
    adresse: "Avenue de l'Indépendance, Immeuble Sahel",
    ville: "Ségou",
    pays: "Mali",
    contactPrincipal: "Fatoumata Diallo",
    conditionsPaiement: "50 % à la commande, 50 % à la livraison",
    delaiLivraisonJours: 10,
    notes: "Livraisons groupées le mardi. Bon suivi des délais.",
    logo: null,
    favori: true,
    actif: true,
    dateCreation: j(540),
  },
  {
    id: "F-003",
    nom: "Beauty Africa Group",
    entreprise: "Beauty Africa Group Ltd",
    telephone: "+225 27 20 41 55",
    whatsapp: "+225 07 58 41 55",
    email: "sales@beautyafrica.ci",
    adresse: "Boulevard Valéry Giscard d'Estaing, Zone 4",
    ville: "Abidjan",
    pays: "Côte d'Ivoire",
    contactPrincipal: "Aïcha Kouassi",
    conditionsPaiement: "Paiement anticipé par virement",
    delaiLivraisonJours: 18,
    notes: "Importation sérums et coffrets. Prévoir les délais de douane.",
    logo: null,
    favori: false,
    actif: true,
    dateCreation: j(430),
  },
  {
    id: "F-004",
    nom: "Atelier 501",
    entreprise: "Atelier 501 — Production locale",
    telephone: "+223 66 90 17 04",
    whatsapp: "+223 66 90 17 04",
    email: "atelier@501.ml",
    adresse: "Quartier Kalaban Coura, Rue 118",
    ville: "Bamako",
    pays: "Mali",
    contactPrincipal: "Bakary Sora",
    conditionsPaiement: "Paiement comptant",
    delaiLivraisonJours: 3,
    notes: "Atelier interne : savons, beurre de karité et coffrets sur mesure.",
    logo: null,
    favori: true,
    actif: true,
    dateCreation: j(900),
  },
  {
    id: "F-005",
    nom: "Karité Nature Koulikoro",
    entreprise: "Coopérative Karité Nature",
    telephone: "+223 74 55 21 30",
    whatsapp: "+223 74 55 21 30",
    email: "cooperative@karitenature.ml",
    adresse: "Route de Koulikoro, Km 12",
    ville: "Koulikoro",
    pays: "Mali",
    contactPrincipal: "Salimata Coulibaly",
    conditionsPaiement: "Paiement à la livraison",
    delaiLivraisonJours: 5,
    notes: "Matière première karité. Qualité irrégulière en saison des pluies.",
    logo: null,
    favori: false,
    actif: true,
    dateCreation: j(300),
  },
  {
    id: "F-006",
    nom: "Emballages Niger Plus",
    entreprise: "Emballages Niger Plus",
    telephone: "+227 20 73 66 21",
    whatsapp: "+227 90 73 66 21",
    email: "info@embnigerplus.ne",
    adresse: "Quartier Plateau, Rue du Commerce",
    ville: "Niamey",
    pays: "Niger",
    contactPrincipal: "Idrissa Hamidou",
    conditionsPaiement: "Paiement à 15 jours",
    delaiLivraisonJours: 21,
    notes: "Flacons et étiquettes. Aucune commande depuis plusieurs mois.",
    logo: null,
    favori: false,
    actif: false,
    dateCreation: j(650),
  },
];

const evt = (date: string, libelle: string, utilisateur = "Bekaye Sora") => ({
  date,
  libelle,
  utilisateur,
});

export const commandesDemo: CommandeAchat[] = [
  {
    id: "C-001",
    numero: "CMD-2026-0001",
    date: j(58),
    fournisseurId: "F-001",
    dateLivraisonPrevue: j(50),
    dateReception: j(49),
    modePaiement: "Paiement à 30 jours",
    observation: "Réassort trimestriel des lotions.",
    responsable: "Bekaye Sora",
    statut: "recue",
    lignes: [
      { produitId: "P-001", nom: "Lotion Éclaircissante 501", quantite: 200, prixAchat: 3200, remise: 5 },
      { produitId: "P-004", nom: "Crème Hydratante 501", quantite: 120, prixAchat: 4100, remise: 0 },
    ],
    historique: [
      evt(j(58), "Commande créée"),
      evt(j(57), "Commande envoyée au fournisseur"),
      evt(j(55), "Commande confirmée par le fournisseur"),
      evt(j(49), "Commande réceptionnée — stock mis à jour"),
    ],
    commentaires: [
      { id: "K-1", date: j(55), auteur: "Moussa Traoré", texte: "Livraison prévue avec un jour d'avance." },
    ],
  },
  {
    id: "C-002",
    numero: "CMD-2026-0002",
    date: j(41),
    fournisseurId: "F-004",
    dateLivraisonPrevue: j(38),
    dateReception: j(38),
    modePaiement: "Paiement comptant",
    observation: "Production locale savons et karité.",
    responsable: "Aminata Doumbia",
    statut: "recue",
    lignes: [
      { produitId: "P-002", nom: "Savon 501", quantite: 400, prixAchat: 650, remise: 0 },
      { produitId: "P-011", nom: "Beurre de Karité 501", quantite: 150, prixAchat: 1800, remise: 10 },
    ],
    historique: [
      evt(j(41), "Commande créée", "Aminata Doumbia"),
      evt(j(41), "Commande envoyée au fournisseur", "Aminata Doumbia"),
      evt(j(38), "Commande réceptionnée — stock mis à jour", "Aminata Doumbia"),
    ],
    commentaires: [],
  },
  {
    id: "C-003",
    numero: "CMD-2026-0003",
    date: j(27),
    fournisseurId: "F-003",
    dateLivraisonPrevue: j(9),
    dateReception: j(6),
    modePaiement: "Virement bancaire",
    observation: "Import sérums et coffrets cadeaux.",
    responsable: "Bekaye Sora",
    statut: "recue",
    lignes: [
      { produitId: "P-006", nom: "Sérum Éclat 501", quantite: 90, prixAchat: 6200, remise: 0 },
      { produitId: "P-008", nom: "Coffret Découverte 501", quantite: 60, prixAchat: 9500, remise: 7 },
    ],
    historique: [
      evt(j(27), "Commande créée"),
      evt(j(26), "Commande envoyée au fournisseur"),
      evt(j(20), "Commande confirmée par le fournisseur"),
      evt(j(12), "Commande expédiée"),
      evt(j(6), "Commande réceptionnée — stock mis à jour"),
    ],
    commentaires: [
      { id: "K-2", date: j(12), auteur: "Aïcha Kouassi", texte: "Dossier de dédouanement transmis." },
    ],
  },
  {
    id: "C-004",
    numero: "CMD-2026-0004",
    date: j(14),
    fournisseurId: "F-002",
    dateLivraisonPrevue: j(3),
    dateReception: null,
    modePaiement: "50 % à la commande, 50 % à la livraison",
    observation: "Réassort gel douche et lait de toilette.",
    responsable: "Bekaye Sora",
    statut: "expediee",
    lignes: [
      { produitId: "P-007", nom: "Gel Douche 501 Nature", quantite: 160, prixAchat: 1450, remise: 0 },
      { produitId: "P-009", nom: "Lait de Toilette 501", quantite: 100, prixAchat: 2300, remise: 5 },
    ],
    historique: [
      evt(j(14), "Commande créée"),
      evt(j(13), "Commande envoyée au fournisseur"),
      evt(j(11), "Commande confirmée par le fournisseur"),
      evt(j(6), "Commande expédiée"),
    ],
    commentaires: [
      { id: "K-3", date: j(4), auteur: "Fatoumata Diallo", texte: "Camion bloqué à Ségou, retard de 2 jours." },
    ],
  },
  {
    id: "C-005",
    numero: "CMD-2026-0005",
    date: j(6),
    fournisseurId: "F-001",
    dateLivraisonPrevue: jPlus(4),
    dateReception: null,
    modePaiement: "Paiement à 30 jours",
    observation: "Commande urgente — stock lotion en tension.",
    responsable: "Bekaye Sora",
    statut: "confirmee",
    lignes: [
      { produitId: "P-001", nom: "Lotion Éclaircissante 501", quantite: 150, prixAchat: 3250, remise: 3 },
      { produitId: "P-012", nom: "Déodorant Fraîcheur 501", quantite: 120, prixAchat: 1250, remise: 0 },
    ],
    historique: [
      evt(j(6), "Commande créée"),
      evt(j(6), "Commande envoyée au fournisseur"),
      evt(j(5), "Commande confirmée par le fournisseur"),
    ],
    commentaires: [],
  },
  {
    id: "C-006",
    numero: "CMD-2026-0006",
    date: j(2),
    fournisseurId: "F-005",
    dateLivraisonPrevue: jPlus(3),
    dateReception: null,
    modePaiement: "Paiement à la livraison",
    observation: "Matière première karité pour l'atelier.",
    responsable: "Aminata Doumbia",
    statut: "envoyee",
    lignes: [
      { produitId: "P-011", nom: "Beurre de Karité 501", quantite: 200, prixAchat: 1750, remise: 0 },
    ],
    historique: [
      evt(j(2), "Commande créée", "Aminata Doumbia"),
      evt(j(2), "Commande envoyée au fournisseur", "Aminata Doumbia"),
    ],
    commentaires: [],
  },
  {
    id: "C-007",
    numero: "CMD-2026-0007",
    date: j(1),
    fournisseurId: "F-004",
    dateLivraisonPrevue: jPlus(6),
    dateReception: null,
    modePaiement: "Paiement comptant",
    observation: "Brouillon en attente de validation du budget.",
    responsable: "Bekaye Sora",
    statut: "brouillon",
    lignes: [
      { produitId: "P-010", nom: "Éponge Exfoliante 501", quantite: 250, prixAchat: 450, remise: 0 },
      { produitId: "P-003", nom: "Lingettes 501", quantite: 180, prixAchat: 900, remise: 0 },
    ],
    historique: [evt(j(1), "Commande créée")],
    commentaires: [],
  },
];

export const notificationsFournisseursDemo: NotificationFournisseur[] = [
  {
    id: "NF-1",
    date: j(0),
    type: "retard",
    titre: "Livraison en retard",
    message: "La commande CMD-2026-0004 (Distribution Sahel) devait arriver il y a 3 jours.",
  },
  {
    id: "NF-2",
    date: j(1),
    type: "commande",
    titre: "Commande envoyée",
    message: "CMD-2026-0006 a été transmise à Karité Nature Koulikoro.",
  },
  {
    id: "NF-3",
    date: j(6),
    type: "reception",
    titre: "Commande reçue",
    message: "CMD-2026-0003 (Beauty Africa Group) a été réceptionnée, le stock a été mis à jour.",
  },
];
